Repository Murphyly/mate85_ecommerce, pull requests merged in 2023-11, with the labels that each got.

#76 fix(product): :ambulance: Corrigido erro grave que duplicou código
  app/(website)/product/[id]/page.js
Labels: bug

#89 [issue-70] fix: :bug: made updateProduct form fields editable
  components/admin/adminForm.jsx
Labels: bug, frontend

#88 [issue-86] fix: :bug: removed unused header's links
  components/navbar.jsx
Labels: enhancement, frontend

#95 [issue-86] feat: melhorias gerais na home page
  app/(website)/page.js
  components/categories/Sidebar.jsx
  components/navbar.jsx
  components/ui/mutiRangeSlider/multiRangeSlider.css
  components/ui/mutiRangeSlider/multiRangeSlider.jsx
Labels: enhancement, frontend

#97 Implementação de roles por usuários
  app/(website)/user/actions.js
  app/(website)/user/page.js
  app/(website)/user/userOrders.jsx
  app/admin/dashboard/actions.js
  app/admin/layout.js
  app/admin/order/actions.js
  app/admin/products/actions.js
  app/admin/products/categories/add/action.js
  app/admin/products/edit/[id]/actions.js
  app/admin/settings/actions.js
  app/admin/users/edit/[id]/actions.js
  app/admin/users/edit/[id]/page.js
  app/admin/users/manage/actions.js
  app/admin/users/page.js
  app/api/auth/[...nextauth]/route.js
  components/admin/adminForm.jsx
  components/admin/navbar.jsx
  components/footer.jsx
  components/navbar.jsx
  prisma/migrations/20231115125547_user_role/migration.sql
  prisma/migrations/20231115133008_default_user_role/migration.sql
  prisma/migrations/20231115134556_remove_unused_user_attributes/migration.sql
  prisma/migrations/20231115151037_default_name_empty/migration.sql
  prisma/schema.prisma
  s.city,
  utils/sampledata.js
Labels: backend, frontend

#99 Múltiplos pequenos fixes
  app/(website)/cart/page.js
  app/(website)/checkout/actions.js
  app/(website)/checkout/page.js
  app/(website)/page.js
  app/(website)/product/[id]/page.js
  app/(website)/user/actions.js
  app/(website)/user/page.js
  app/admin/dashboard/components/ordersTable.js
  app/admin/dashboard/page.js
  app/admin/settings/page.js
  components/categories/Sidebar.jsx
  components/order/productList.jsx
  components/ui/cartItem.jsx
  components/ui/filtros.jsx
  components/ui/readmore.jsx
  components/ui/review.jsx
Labels: bug, enhancement, backend, frontend

#104 raw: :pencil: added order status translator
  app/admin/dashboard/components/ordersTable.js
  utils/orderStatusTranslator.js
Labels: enhancement, frontend
